
version: '3.7'


services:
  api:
    image: crimes-api
    container_name: crimes-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
     - '8001:8001'
    depends_on:
      - mongodb
      - graphdb
    volumes:
      - ./backend:/app


  # frontend:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: main-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  graphdb:
    image: neo4j:5.12.0
    container_name: graph-db
    restart: unless-stopped
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - neo4j-data:/data
    environment:
      NEO4J_AUTH: "neo4j/pleaseletmein"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'


volumes:
  mongo-data:
  neo4j-data: